services:
  api:
    image: ${DOCKER_REGISTRY-}api-2
    build:
      context: .
      dockerfile: API/Dockerfile


  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=ProductsDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432

