version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile


  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

